### ISSUE TITLE
ERROR: cannot download default sources list from.. while running "./build.sh"

### ISSUE THREAD

**Issue by HowieHepburn** [umautobots/LONER#11] opened 2023-12-14 06:46 UTC
=> ERROR [ 7/10] RUN sudo rosdep init && rosdep update                    0.5s
------
 > [ 7/10] RUN sudo rosdep init && rosdep update:
0.466 ERROR: cannot download default sources list from:
0.466 https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
0.466 Website may be down.
------
container_local.Dockerfile:27
--------------------
  25 |     
  26 |     RUN sudo chown -R ${USER_NAME} /home/${USER_NAME}
  27 | >>> RUN sudo rosdep init && rosdep update
  28 |     
  29 |     # finish ROS setup
--------------------
ERROR: failed to solve: process "/bin/sh -c sudo rosdep init && rosdep update" did not complete successfully: exit code: 4

I can normally running rosdep init && rosdep update ,and I can access the web https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list

**Comment by rahulswa08** [comment] 2024-01-06 22:44
Hello @HowieHepburn,

I tried running `./build.sh` but was unable to reproduce the error. It's likely that the problem would be related to the network or docker. Here are a few suggestions which you can try to narrow down the cause of the issue. 

1. Have you modified the base image? or using the default base image `BASE_IMAGE=sethgi/loner:base_1.0` ( line 1 container_local.Dockerfile)? If yes they can have some dependency issues. ([ref](https://github.com/ros-infrastructure/rosdep/issues/666))
2. Try building the container without line 27 and run the `sudo rosdep init && rosdep update` inside the container.
3. Try building docker using sudo user as mentioned [here](https://answers.ros.org/question/241112/how-to-run-rosdep-init-and-update-in-dockerfile/).

I would also recommend trying to run the rosdep on an entirely new dockerfile to check if it's not the problem because of docker compatibility.

**Comment by sethgi** [comment] 2024-01-29 17:04
@HowieHepburn  Did you manage to sort this out? I'm going to close this issues in a couple days if I don't hear back.

**Closed as not planned** 2024-02-01 19:13 UTC
Labels: docker
